config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  root 'pages#one'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/one.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hugo moraga</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>

app/views/pages/three.html.erb
<h2>  Lorem ipsum dolor </h2>

<p>Lorem ipsum dolor sit amet consectetur adipiscing elit enim quis condimentum faucibus, porta orci torquent dui phasellus tincidunt dignissim potenti mattis posuere, sodales eros fermentum odio porttitor laoreet rhoncus ante praesent risus. Ut felis himenaeos hac tempor massa dictum sollicitudin, ridiculus ac nostra porta sem orci aenean libero, nunc cursus nisl parturient tristique pellentesque. Ante justo porttitor rhoncus libero neque praesent inceptos, per pellentesque blandit conubia interdum nullam molestie hac, ridiculus aliquet et feugiat rutrum tellus.

Est erat neque mattis blandit tempus laoreet nisi, aliquet taciti platea pretium condimentum morbi hac, facilisi bibendum magnis maecenas cursus auctor. Vitae magna vulputate ornare fusce class justo maecenas, per ultrices etiam egestas pulvinar platea ut taciti, convallis eu hendrerit euismod enim vehicula. Convallis habitant integer praesent enim ullamcorper habitasse laoreet sociis ad sociosqu a malesuada turpis class, ac sed condimentum taciti mus est potenti imperdiet orci fringilla neque id. </p>

app/views/pages/two.html.erb
<h1>Pages#two</h1>

<%= image_tag("Selección_001.png", :alt => "rails routes") %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg  navbar-light bg-ligh">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "One", pages_one_path, class: 'nav-link' %>
    </li>
       <li class="nav-item">
        <%= link_to "Two", pages_two_path, class: 'nav-link' %>
    </li>
       <li class="nav-item">
        <%= link_to "Three", pages_three_path, class: 'nav-link' %>
    </li>

    </ul>

  </div>
</nav>